workflows:
  ios-workflow:
    name: Build iOS Calculadora 30%
    environment:
      vars:
        XCODE_PROJECT: "Calculadora30.xcodeproj"
        XCODE_SCHEME: "Calculadora30"
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild -project "$XCODE_PROJECT"           -scheme "$XCODE_SCHEME"           -sdk iphoneos           -configuration Release           build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/**/*.ipa
      - build/**/*.app
