workflows:
  ios-workflow:
    name: Build iOS Calculadora 30%
    environment:
      xcode: latest
    scripts:
      - name: Instalar XcodeGen
        script: |
          brew update
          brew install xcodegen
      - name: Gerar projeto Xcode
        script: |
          xcodegen generate --spec project.yml
          mv Calculadora30.xcodeproj Calculadora30.xcodeproj
          ls -la
      - name: Compilar app iOS (sem assinatura)
        script: |
          xcodebuild -project "Calculadora30.xcodeproj" \
          -scheme "Calculadora30" \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
          build
    artifacts:
      - build/**/*.app
      - build/**/*.ipa
